#!/bin/bash

verilator ../../hdl/*.v --cc --top-module jtdsp16 --exe test.cc vcd.cc rtl.cc mametrace.cc WaveWritter.cc \
    --trace -DJTDSP16_DEBUG -DJTDSP16_DUMP || exit $?
export CPPFLAGS=-O3
make -j -C obj_dir -f Vjtdsp16.mk Vjtdsp16 || exit $?

if which vcd2fst; then
    sim $* -vcd >(vcd2fst -v - -f test.fst)
else
    sim $* -vcd test.vcd
fi